---

vlans: "2-20,99"

trunk_vlans: "2-20"
native: 99

named_spine_vlans:
  - { vlan_id: 10, name: ansible_test_segment_1 }
  - { vlan_id: 20, name: ansible_test_segment_2 }
  - { vlan_id: 99, name: native }


default_trunk_interfaces:
  - Ethernet1/1
  - Ethernet1/2

logical_interfaces_to_create:
  - vlan10
  - vlan20

layer3ip:
  - { interface: vlan10, ip: 10.1.10.10, mask: 24 }
  - { interface: vlan20, ip: 10.1.20.10, mask: 24 }
